### PR TITLE
only output actual error messages on stderr; stratux listens to stder…

### PR DESCRIPTION
**Pull request by jpoirier**
…r and shuts down the dump1090 process when one is received

and some white space removal

### CODE REVIEW

**Comment by AvSquirrel** [comment]
I moved from dump1090-MalcolmRobb to dump1090-mutability at Stratux commit 5d082e3 -- but didn't make it my dump1090 master until just now.

I'll manually incorpororate your changes to test. Stand by.

**Comment by AvSquirrel** [comment]
Shouldn't these be on `stdout`, not `stdio`?

**Comment by AvSquirrel** [comment]
Testing now on c4589a2a

**Comment by AvSquirrel** [comment]
Moved additional nonfatal errors to stdout: 98bf669

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 8:53 AM, AvSquirrel <notifications@github.com>
wrote:

> Shouldn't these be on stdout, not stdio?
>
Yup. Sorry about that.

**Comment by jpoirier** [comment]
I think stratux is pointing to the mutability branch?

**Comment by AvSquirrel** [comment]
> I think stratux is pointing to the mutability branch?

Yes, but you pulled from my MalcolmRobb branch. I had left mutability on its own branch while we evaluated it. Since it's in an "official" Stratux release now, I merged mutability changes into my master dump1090 branch this morning. So, less confusion going forward.

I've played with your proposed changes to sdr.go, and I'm not sure this is going to be the easiest way to accomplish what you want to do. Not only do other dump1090 source files also send diagnostics to stderr, but so does librtlsdr.rtlsdr_open() ("Found Rafael Micro R820T tuner"). I could update dump1090 as needed, but would have to trap / redirect any nonfatal stderr output from upstream.

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 12:27 PM, AvSquirrel <notifications@github.com>
wrote:

> I think stratux is pointing to the mutability branch?
>
> Yes, but you pulled from my MalcolmRobb branch. I had left mutability on
> its own branch while we evaluated it. Since it's in an "official" Stratux
> release now, I merged mutability changes into my master dump1090 branch
> this morning. So, less confusion going forward.
>
Yup, I hadn't realized which branch was being used until after you'd
commented, my comment was based on your changes which you merged to master
already so ignore my comment.

> I've played with your proposed changes to sdr.go, and I'm not sure this is
> going to be the easiest way to accomplish what you want to do. Not only do
> other dump1090 source files also send diagnostics to stderr, but so does
> librtlsdr.rtlsdr_open() ("Found Rafael Micro R820T tuner"). I could update
> dump1090 as needed, but would have to trap / redirect any nonfatal stderr
> output from upstream.
>
Okay, makes sense. Yeah, using stderr that way would have been easy but
it'd be a nasty hack. Maybe register an atexit function in dump1090 that
writes to an agreed upon named piped?

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 12:27 PM, AvSquirrel <notifications@github.com>
wrote:

> I've played with your proposed changes to sdr.go, and I'm not sure this is
> going to be the easiest way to accomplish what you want to do.
>
I'm assuming by proposed changes you're referring to the commented out code
in the pull request and not the PR itself?

**Comment by jpoirier** [comment]
On Sat, Mar 12, 2016 at 1:15 PM, Joseph Poirier <jdpoirier@gmail.com> wrote:

> On Sat, Mar 12, 2016 at 12:27 PM, AvSquirrel <notifications@github.com>
> wrote:
>
>> I've played with your proposed changes to sdr.go, and I'm not sure this
>> is going to be the easiest way to accomplish what you want to do. Not only
>> do other dump1090 source files also send diagnostics to stderr, but so does
>> librtlsdr.rtlsdr_open() ("Found Rafael Micro R820T tuner"). I could update
>> dump1090 as needed, but would have to trap / redirect any nonfatal stderr
>> output from upstream.
>>
> Okay, makes sense. Yeah, using stderr that way would have been easy but
> it'd be a nasty hack. Maybe register an atexit function in dump1090 that
> writes to an agreed upon named piped?
>

After thinking about it for a minute, it'd be easier just to periodically
do a pgrep to check if it's alive.

**Pull request closed without merging**
